### PR TITLE
Style cleanup

### PR DESCRIPTION
**Pull request by justin-summerlin**
Includes style changes to match the Inkling internal style and some minor logic cleanup.

https://github.com/inkling/htmldiff.js/pull/11 relies on this.

### CODE REVIEW

**Comment by justin-summerlin** [comment]
This diff is gross, sorry about that :disappointed:

**Comment by loganfsmyth** [comment]
I reviewed it with `?w=` in the URL which helps. Seems reasonable. As long as the tests pass and Habitat looks fine, I'm happy. There are a few behavior changes but nothing that seems like it would make a difference in real code.

**Comment by justin-summerlin** [comment]
All of the mocha tests pass as well as the Habitat tests, and I haven't seen any issues with side by side or review edits.

**Comment by BradNeuberg** [comment]
I don't know, maybe you should change tabs to spaces?

jk, I'm still included in htmldiff changes. Just causing trouble.

**Comment by loganfsmyth** [comment]
@BradNeuberg get outta here :P

**Pull request merged**
